/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root Health
         * @description Bare-root liveness check for container orchestrators
         *     (milestone5_plan.md §2.3) — identical to ``GET /api/health``.
         */
        get: operations["root_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meta
         * @description Every scenario preset, dimension label and limitations string the
         *     frontend needs — fetched once at boot so none of it is hand-duplicated
         *     in TypeScript (milestone5_plan.md §2.6).
         */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diseases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Diseases */
        get: operations["list_diseases_api_diseases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diseases/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Diseases Endpoint */
        get: operations["search_diseases_endpoint_api_diseases_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diseases/{disease_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disease Detail */
        get: operations["disease_detail_api_diseases__disease_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rank
         * @description Rank candidate targets for a disease — the same scoring path the
         *     Streamlit app uses (milestone3_plan.md §2), now reaching every filter,
         *     the scenario weights, and the sort toggle (milestone5_plan.md §1).
         */
        post: operations["rank_api_rank_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evidence
         * @description The target-detail evidence card (Context.md §21, §37) — the exact
         *     weighted-baseline contribution breakdown plus the held-out XGBoost
         *     fold model's live SHAP explanation, matching
         *     ``services.evidence_summary.build_evidence_card`` (milestone3_plan.md
         *     §2), extended with the raw ``contrib__``/``dim__`` values the
         *     evidence-breakdown chart and radar need (milestone5_plan.md §2.5).
         */
        post: operations["evidence_api_evidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DiseaseDetailResponse */
        DiseaseDetailResponse: {
            /** Disease Id */
            disease_id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Therapeutic Areas */
            therapeutic_areas?: string[];
            /** N Associated Targets */
            n_associated_targets?: number | null;
            /** Evidence Categories Built */
            evidence_categories_built: number;
            /** Evidence Categories Total */
            evidence_categories_total: number;
            /** Evidence Coverage */
            evidence_coverage: components["schemas"]["EvidenceCategoryStatus"][];
            /** Dataset Version */
            dataset_version?: string | null;
            /** Extraction Date */
            extraction_date?: string | null;
        };
        /** DiseaseSummaryResponse */
        DiseaseSummaryResponse: {
            /** Disease Id */
            disease_id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Therapeutic Areas */
            therapeutic_areas?: string[];
            /** N Associated Targets */
            n_associated_targets?: number | null;
        };
        /**
         * EvidenceBreakdown
         * @description All five of WeightedBaseline's scored dimensions, plus the three
         *     categories that are computed (Milestone 4) but never enter the
         *     weighted-baseline formula the ranking table's default scenario controls
         *     are restricted to (presentation.DIMENSION_KEYS) — those three, and
         *     safety (no scored weight per Context.md §14.7), report null here by
         *     design, not by omission. `evidence_completeness` on the parent response
         *     is what actually reflects all six built categories; the evidence-detail
         *     endpoint (`/api/evidence`) is where a target's pathway/expression/
         *     network standing is surfaced (its `missing` list) and where safety
         *     appears as a contradicting-evidence flag.
         */
        EvidenceBreakdown: {
            /** Genetics */
            genetics?: number | null;
            /** Evidence Diversity */
            evidence_diversity?: number | null;
            /** Functional */
            functional?: number | null;
            /** Literature */
            literature?: number | null;
            /** Druggability */
            druggability?: number | null;
            /** Pathways */
            pathways?: number | null;
            /** Expression */
            expression?: number | null;
            /** Network */
            network?: number | null;
            /** Safety */
            safety?: number | null;
        };
        /** EvidenceCategoryStatus */
        EvidenceCategoryStatus: {
            /** Category */
            category: string;
            /** Built */
            built: boolean;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** EvidenceItemResponse */
        EvidenceItemResponse: {
            /** Category */
            category: string;
            /** Value */
            value?: number | string | null;
            /** Source */
            source: string;
            /** Source Url */
            source_url?: string | null;
            /** Dataset Version */
            dataset_version?: string | null;
        };
        /** EvidenceRequest */
        EvidenceRequest: {
            /** Disease Id */
            disease_id: string;
            /** Target Id */
            target_id: string;
            /** Weights */
            weights?: {
                [key: string]: number;
            } | null;
        };
        /** EvidenceResponse */
        EvidenceResponse: {
            /** Disease Id */
            disease_id: string;
            /** Target Id */
            target_id: string;
            /** Gene Symbol */
            gene_symbol: string;
            /** Gene Name */
            gene_name: string;
            /**
             * Score
             * @description Weighted-baseline score — the evidence card's score is always this one, never the XGBoost score (services.evidence_summary module docstring); XGBoost's contribution is surfaced separately, tagged by source, in `supporting`/`contradicting`.
             */
            score: number;
            /** Weights Used */
            weights_used: {
                [key: string]: number;
            };
            /**
             * Contributions
             * @description contrib__<dimension> — sums exactly to `score` (WeightedBaseline.explain; no approximation). The evidence-breakdown bar chart's data.
             */
            contributions: {
                [key: string]: number;
            };
            /**
             * Dimension Values
             * @description Raw dim__<dimension> values, nulls preserved (invariant 1) — the evidence radar's data. A null here means no evidence was recorded, not a zero score.
             */
            dimension_values: {
                [key: string]: number | null;
            };
            /** Supporting */
            supporting?: components["schemas"]["EvidenceItemResponse"][];
            /** Contradicting */
            contradicting?: components["schemas"]["EvidenceItemResponse"][];
            /** Missing */
            missing?: string[];
            /** Xgboost Score Held Out */
            xgboost_score_held_out?: number | null;
            /** N Other Diseases Positive */
            n_other_diseases_positive?: number | null;
            /**
             * Rank
             * @description This target's rank among every candidate for the disease under `weights_used`.
             */
            rank?: number | null;
            /** Total Candidates */
            total_candidates?: number | null;
            /**
             * Label N Drugs
             * @description Existing-drug/clinical-stage evidence the training label is built from (Context.md §15) — for context only, never a ranking input (invariant 3).
             */
            label_n_drugs?: number | null;
            /** Label Drug Names */
            label_drug_names?: string | null;
            /** Label Max Clinical Stage */
            label_max_clinical_stage?: number | null;
            /**
             * Not Buildable
             * @description Items Context.md §21/§37/§38.4 ask for that nothing in the pipeline computes yet (direction of effect, confidence level) — render as a labelled placeholder, never a blank or a zero.
             */
            not_buildable?: {
                [key: string]: string;
            };
            /** Source Links */
            source_links?: {
                [key: string]: string;
            };
            /** Limitations */
            limitations?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Dataset Version */
            dataset_version?: string | null;
            /**
             * Model Loaded
             * @default false
             */
            model_loaded: boolean;
        };
        /**
         * MetaResponse
         * @description Every UI-facing constant the frontend needs at boot, fetched once
         *     (milestone5_plan.md §4.1) so no scenario preset, dimension label, or
         *     limitations string is hand-duplicated in TypeScript.
         */
        MetaResponse: {
            /** Scenario Presets */
            scenario_presets: components["schemas"]["ScenarioPresetResponse"][];
            safety_first: components["schemas"]["ScenarioPresetResponse"];
            /** Custom Slug */
            custom_slug: string;
            /** Custom Label */
            custom_label: string;
            /** Dimension Keys */
            dimension_keys: string[];
            /** Dimension Labels */
            dimension_labels: {
                [key: string]: string;
            };
            /** Evidence Categories */
            evidence_categories: string[];
            /** Unavailable Evidence Categories */
            unavailable_evidence_categories: {
                [key: string]: string;
            };
            /** Not Buildable */
            not_buildable: {
                [key: string]: string;
            };
            /** Default Weights */
            default_weights: {
                [key: string]: number;
            };
            /** Limitations */
            limitations?: string[];
        };
        /** RankedTargetResponse */
        RankedTargetResponse: {
            /**
             * Rank
             * @description Position among ALL candidates for this disease, before filters truncate the list — gaps are expected (invariant 9).
             */
            rank: number;
            /** Target Id */
            target_id: string;
            /** Gene Symbol */
            gene_symbol: string;
            /** Gene Name */
            gene_name: string;
            /**
             * Score
             * @description The active sort's score (NOT a probability of success)
             */
            score: number;
            /**
             * Sort By
             * @enum {string}
             */
            sort_by: "weighted_baseline" | "xgboost_held_out";
            /** Weighted Baseline Score */
            weighted_baseline_score: number;
            /** Xgboost Score Held Out */
            xgboost_score_held_out?: number | null;
            evidence: components["schemas"]["EvidenceBreakdown"];
            /**
             * Evidence Completeness
             * @description Fraction (0-1) of the six built evidence categories present for this target. Never render as a bare fraction (invariant 2) — use evidence_completeness_count / evidence_completeness_total.
             */
            evidence_completeness: number;
            /** Evidence Completeness Count */
            evidence_completeness_count: number;
            /** Evidence Completeness Total */
            evidence_completeness_total: number;
            /** Missing Evidence */
            missing_evidence?: string[];
            /** N Other Diseases Positive */
            n_other_diseases_positive?: number | null;
            /** Source Links */
            source_links?: {
                [key: string]: string;
            };
        };
        /**
         * RankingFiltersRequest
         * @description Mirrors ``services.target_ranking.RankingFilters`` field for field —
         *     including ``target_family``, which stays unbuildable (invariant 6): the
         *     field exists so a client that sets it gets a 400 with the reason,
         *     rather than the request silently omitting a filter the caller believes
         *     is applied.
         */
        RankingFiltersRequest: {
            /** Min Genetics Evidence */
            min_genetics_evidence?: number | null;
            /**
             * Require Druggable
             * @default false
             */
            require_druggable: boolean;
            /**
             * Relevant Tissue
             * @description Detectable expression in the disease's configured tissues — a switch, not a free-text tissue (RankingFilters.relevant_tissue's docstring).
             * @default false
             */
            relevant_tissue: boolean;
            /** Min Evidence Completeness */
            min_evidence_completeness?: number | null;
            /**
             * Exclude Safety Concerns
             * @default false
             */
            exclude_safety_concerns: boolean;
            /**
             * Target Family
             * @description Not buildable in this release (needs target.targetClass). Setting this returns HTTP 400 rather than silently ignoring it.
             */
            target_family?: string | null;
        };
        /** RankingRequest */
        RankingRequest: {
            /**
             * Disease Id
             * @description Open Targets disease ID, e.g. MONDO_0005180
             */
            disease_id: string;
            /**
             * Top N
             * @default 50
             */
            top_n: number;
            /**
             * Weights
             * @description Scenario weights (Context.md §38.5). Any positive combination — normalized server-side; the normalized values used are echoed back in `weights_used`. Defaults to configs/model.yaml's milestone_1_weights.
             */
            weights?: {
                [key: string]: number;
            } | null;
            /**
             * Sort By
             * @default weighted_baseline
             * @enum {string}
             */
            sort_by: "weighted_baseline" | "xgboost_held_out";
            filters?: components["schemas"]["RankingFiltersRequest"];
        };
        /** RankingResponse */
        RankingResponse: {
            /** Disease Id */
            disease_id: string;
            /** Disease Name */
            disease_name: string;
            /**
             * Sort By
             * @enum {string}
             */
            sort_by: "weighted_baseline" | "xgboost_held_out";
            /**
             * Weights Used
             * @description Normalized weights actually applied — display THESE next to the score, never the raw slider values a client may have sent.
             */
            weights_used: {
                [key: string]: number;
            };
            /** Targets */
            targets: components["schemas"]["RankedTargetResponse"][];
            /**
             * Total Candidates
             * @description Every candidate target for this disease before any filter or top_n truncation — the denominator for a partial export label (milestone5_plan.md §2.7).
             */
            total_candidates: number;
            /** Dataset Version */
            dataset_version: string;
            /** Model Version */
            model_version: string;
            /** Limitations */
            limitations?: string[];
        };
        /** ScenarioPresetResponse */
        ScenarioPresetResponse: {
            /** Slug */
            slug: string;
            /** Label */
            label: string;
            /** Weights */
            weights: {
                [key: string]: number;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    list_diseases_api_diseases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiseaseSummaryResponse"][];
                };
            };
        };
    };
    search_diseases_endpoint_api_diseases_search_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiseaseSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disease_detail_api_diseases__disease_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                disease_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiseaseDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rank_api_rank_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_api_evidence_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
